apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-svc
  labels:
    app: submission-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-svc
  template:
    metadata:
      labels:
        app: submission-svc
    spec:
      containers:
        - name: submission-svc
          image: ghcr.io/flawmop/submission-svc
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          volumeMounts:
            - name: submission-config-volume
              mountPath: /workspace/config
      volumes:
        - name: submission-config-volume
          configMap:
            name: submission-config
