apiVersion: v1
kind: Service
metadata:
  name: run-input-processing-svc
  labels:
    app: run-input-processing-svc
spec:
  type: ClusterIP
  selector:
    app: run-input-processing-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9002
